# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        deno: [1.0.5, 0.42.0]
    name: Deno ${{ matrix.deno }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@master

      - name: Setup Deno environment
        uses: denolib/setup-deno@master
        with:
          # Version range or exact version of a Deno version to use.
          deno-version: ${{ matrix.deno }}

      # Runs a set of commands using the runners shell
      - name: Run tests
        run: deno test --allow-net --allow-read

      - name: Test deno install
        run: |
          deno install --allow-read --allow-net --allow-write --unstable -f -n json-server ./server.ts
          cd ./example
          json-server db.json
